routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group([
    'namespace' => 'Admin', // it is added in controller function name
    'prefix' => 'admin', //it is added in url
    'as' => 'admin.' //route name
], function () {
    Route::get('', 'AuthController@index');
    Route::get('logout', 'AuthController@Logout')->name('Logout');
    Route::get('dashboard', 'AuthController@Dashboard')->name('Dashboard');

    Route::get('upcomming/ride', 'RideController@UpcomingRides')->name('UpcomingRides');
    Route::get('city/list', 'CommanController@cityManagement')->name('cityMgnt');
    Route::post('city/add', 'CommanController@addCity')->name('addCity');
    Route::post('city/status/change', 'CommanController@changeStatusCity')->name('changeStatusCity');
    Route::post('city/delete', 'CommanController@deleteCity')->name('deleteCity');
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable=['name','state','latitude','longitude','status'];
    const Active=1,Deactive=2;
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/admin/AuthController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function index()
    {
        return view('admin.login');
    }

    public function Logout()
    {
        return view('admin.login');
    }

    public function Dashboard()
    {
        return view('admin.dashboard');
    }
}

app/Http/Controllers/admin/CommanController.php
<?php

namespace App\Http\Controllers\Admin;
use App\City;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommanController extends Controller
{
    public function cityManagement()
    {
        $cities=City::all();
        return view('admin.city_list',['cities'=>$cities]);
    }

    public function addCity(Request $request)
    {
        City::create([
           'name'=>$request->searchCity,
           'state'=>$request->state,
           'latitude'=>$request->latitude,
           'longitude'=>$request->longitude,
        ]);

        return redirect(route('admin.cityMgnt'))->with('success_message','City Added Successfully');
    }

    public function changeStatusCity(Request $request)
    {
        $this->validate($request, [
            'cityId' => 'required|exists:cities,id'
        ]);

        $city =  City::find($request['cityId']);

        if ($request['status']==1) {
            $status=$city->status = '2';
        } else {
            $status= $city->status = '1';
        }

        $city->save();

        return response()->json([
            'status' => $status
        ]);
    }

    public function deleteCity(Request $request)
    {
        $this->validate($request, [
            'deleteCity' => 'required|exists:cities,id'
        ]);
        $city =City::find($request->deleteCity);
        $city->delete();
    }
}

app/Http/Controllers/admin/RideController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class RideController extends Controller
{
    public function UpcomingRides()
    {
        return view('admin.upcoming_rides');
    }
}

resources/views/admin/city_list.blade.php
@extends('layouts.main')

@section('title')
   Upcoming Rides  | {{env('SITE_NAME')}}
@endsection

@section('content')
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">

            <div class="box box-primary">
                <div class="box-header with-border">
                    <div class="col-md-10">
                        <h3 class="box-title " style="margin-top: 5px;"> List Of City</h3>
                    </div>
                    <div class="col-md-2 ">

                    <a href="#" class="btn btn-block btn-primary btn-sm" data-toggle="modal" data-target="#AddCityModel">Add New City</a>

                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>State</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($cities as $city)
                            <tr>
                                <td>{{$city->id}}</td>
                                <td>{{$city->name}}</td>
                                <td>{{$city->state}}</td>
                                <td>

                                    <a  data-val="{{ $city->id }}"  data-val-status="{{ $city->status }}"
                                        id="status_{{ $city->id }}"
                                        class="status_check @if($city->status == \App\City::Active) {{'label label-success'}} @else {{'label label-danger'}} @endif">@if($city->status == \App\City::Active)  {{ 'Active' }} @else {{'De-Active'}} @endif
                                    </a>
                                </td>
                                <td class="text-center" width="140px">
                                    {{--<a href="javascript:void(0)" class="editicon editcity"> <i class="fa fa-pencil-square fa-2x margin-r-15 margin-l-15" aria-hidden="true"></i></a>--}}
                                    <a href="javascript:void(0)" class="deleteicon deletecity"  data-val="{{$city->id}}"> <i class="fa fa-trash fa-2x " aria-hidden="true"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>State</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->



    <!---- Add New City Model -->
    <div class="modal fade" id="AddCityModel" data-keyboard="false" data-backdrop="false" aria-hidden="true">
        <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Add New City</h4>
                    </div>
                    <form id="addNewCityFrm" method="post" action="{{route('admin.addCity')}}">
                        {{csrf_field()}}
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">City Name</label>
                                <input type="text" class="form-control" id="searchCity" name="searchCity" placeholder="Enter City Name">
                                <input type="hidden" name="latitude" id="latitude">
                                <input type="hidden" name="longitude" id="longitude">
                                <input type="hidden" name="state" id="state">
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
                <!-- /.modal-content -->
            </div>
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!----End  Add New City Model -->
    <!---- Edit City Model -->
    <div class="modal fade" id="EditCityModel">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Edit City</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">City Name</label>
                        <input type="text" class="form-control" id="searchCity1" placeholder="Enter City Name">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Update</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!----End  Edit City Model -->
@endsection


@section('js')


    <script>
        $(function () {
            $('#example1').DataTable();
        })

        $('.editcity').click(function () {
            $('#EditCityModel').modal('show');
        })

        function initialize() {

            var input = document.getElementById('searchCity');
            var options = {
                types: ['(cities)'],
                componentRestrictions: {country: 'IN'}
            };

            var autocomplete = new google.maps.places.Autocomplete($("#searchCity")[0], options);

            google.maps.event.addListener(autocomplete, 'place_changed', function() {
                var place = autocomplete.getPlace();

                var addcomponent=place.address_components;
                var adraddress=place.adr_address;
                console.log(addcomponent);

                var region='';
                var city='';

                for (var i=0; i<addcomponent.length; i++) {
                    for (var b=0;b<addcomponent[i].types.length;b++) {

                        if (addcomponent[i].types[b] == "administrative_area_level_1") {
                            region = addcomponent[i].long_name;
                            break;
                        }
                        if (addcomponent[i].types[b] == "locality") {
                            city = addcomponent[i].long_name;
                            break;
                        }
                    }
                }

                $('#searchCity').val(city);
                $('#state').val(region);
                $('#longitude').val(place.geometry.location.lng());
                $('#latitude').val(place.geometry.location.lat());

            });

        }

        $('.status_check').click(function () {
            var status = $(this).attr('data-val-status');
            var cityId = $(this).attr('data-val');

            if(status==1)
            {
                var msg='De-Activate'
            }
            else
            {
                var msg='Activate'
            }
            swal({
                title: 'Are you sure?',
                text: "You want to " + msg + " this City!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes'
            }).then(function () {
                $.ajax({
                    type: "POST",
                    url: "{{ route('admin.changeStatusCity') }}",
                    data: {
                        _token: '{{ csrf_token() }}',
                        status: status,
                        cityId: cityId
                    },
                    success: function (data) {
                        $('.uk-modal-dialog-replace').hide();
                        var element = $('#status_' + cityId);
                        if (data['status']==1) {
                            var msg='Activated';
                            element.html('Active')
                                .removeClass('label label-danger')
                                .addClass('label label-success');
                        } else {
                            var msg='De-Activated';
                            element.html('De-Active')
                                .removeClass('label label-success')
                                .addClass('label label-danger');
                        }
                        element.val(data['status']);

                        swal({
                            title: 'Good job',
                            text: 'City has been ' + msg + '.',
                            type: 'success',
                            confirmButtonColor: '#3085d6',
                            confirmButtonText: 'Yes'
                        }).then(function () {
                            window.location.reload();
                        });
                    },
                    error: function (xhr, status, error) {
                        $('.overlay').css('display', 'none');
                        swal(
                            'Oops !',
                            'Something went wrong, please try again later.',
                            'warning'
                        );
                    }
                });
            });
        });

        $('.deletecity').on('click', function(e){
            var deleteCity = $(this).attr('data-val');
            swal({
                title: 'Are you sure?',
                text: "You want to Delete this City",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes'
            }).then(function () {
                $.ajax({
                    type: "POST",
                    url: "{{ route('admin.deleteCity') }}",
                    data: {
                        _token: '{{ csrf_token() }}',
                        deleteCity: deleteCity
                    },
                    success: function (data) {
                        swal({
                            title: 'Success!',
                            text: 'City has been removed Successfully.',
                            type: "success",
                            confirmButtonText: "OK"
                        }).then(function () {
                            location.reload();
                        });
                    },
                    error: function (xhr, status, error) {
                        swal(
                            'Oops !',
                            'Something went wrong, please try again later.',
                            'warning'
                        );
                    }
                });
            });
        });

    </script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{env('SITE_NAME')}} | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset("/bower_components/bootstrap/dist/css/bootstrap.min.css")}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset("/bower_components/font-awesome/css/font-awesome.min.css")}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset("/bower_components/Ionicons/css/ionicons.min.css")}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset("/dist/css/AdminLTE.min.css")}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset("/plugins/iCheck/square/blue.css")}}">

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="javascript:void(0)"><b>One Side </b>Cab</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible">
                <h4><i class="icon fa fa-ban"></i> {{session()->get('error')}} </h4>
            </div>
        @endif
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="{{route('admin.Dashboard')}}" method="GET">
            {{csrf_field()}}
            <div class="form-group has-feedback {{ $errors->has('email') ? 'has-error':'' }}">

                <input type="email" name="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                @if($errors->has('email'))
                    <span class="help-block">{{$errors->first('email')}}</span>
                @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('password') ? 'has-error':'' }}">
                <input type="password" class="form-control" name="password" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                @if($errors->has('password'))
                    <span class="help-block">{{$errors->first('password')}}</span>
                @endif
            </div>


            <div class="row">
                <!-- /.col -->
                <div class="col-xs-4 col-xs-offset-4 text-center">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{asset('/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>

</body>
</html>

resources/views/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('bower_components/select2/dist/css/select2.min.css')}}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('dist/css/skins/_all-skins.min.css')}}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{asset('bower_components/morris.js/morris.css')}}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{asset('bower_components/jvectormap/jquery-jvectormap.css')}}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset("/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css")}}">
    <link rel="stylesheet" href="{{ asset("css/developer.css")}}">

    <!-- Select2 -->

    {{--<link rel="stylesheet" href="{{asset('bower_components/bootstrap-multiselect/css/bootstrap-select.min.css')}}">--}}


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>O</b>SC</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>OneSide</b>Cab</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                            Super Admin

                        </a>

                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu offset3">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
                            {{--<span class="hidden-xs">{{Auth::user()->name}}</span>--}}
                            <span class="hidden-xs"> Alexander Pierce</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

                                <p>
                                    Alexander Pierce - Web Devoelper
                                    <small>Member since Nov. 2012</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{{route('admin.Logout')}}" class="btn btn-default btn-flat">Change Password</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{{route('admin.Logout')}}" class="btn btn-default btn-flat">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->

                </ul>
            </div>
        </nav>
    </header>

resources/views/layouts/main.blade.php
<!-- Header -->
@include('header')

<!-- Sidebar -->
@include('sidebar')



@yield('content')



@include('footer')

resources/views/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{{ Request::is( 'admin/dashboard')  ? 'active' : '' }}">
                <a href="{{route('admin.Dashboard')}}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="treeview @if(Request::is( 'admin/upcomming/ride')) menu-open @endif">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Rides</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu" @if(Request::is( 'admin/upcomming/ride')) style="display: block;" @endif>
                    <li @if(Request::is( 'admin/upcomming/ride')) class="active" @endif><a href="{{route('admin.UpcomingRides')}}"><i class="fa fa-circle-o"></i> Upcoming Rides</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Assigned Rides</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Completed Rides</a></li>
                </ul>
            </li>
            <li class="">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Drivers</span>
                </a>
            </li>
            <li class="">
                <a href="{{route('admin.cityMgnt')}}">
                    <i class="fa fa-dashboard"></i> <span>City Management</span>
                </a>
            </li>



            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>Reports</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>